#!/usr/bin/env node
/**
 * Swiss Neo-Monolith — token compiler.
 *
 *   node scripts/build-tokens.mjs
 *
 * Reads tokens/tokens.json (the ONLY hand-edited token file) and emits
 * platform bindings into tokens/dist/. Everything in dist/ is generated;
 * editing it by hand is a bug.
 *
 * tokens/dist/ is also the system's DELIVERY SURFACE: it carries its own
 * package.json and a copy of the lint config, so `scripts/vendor.mjs` can drop
 * the whole directory into a consuming project and every documented import path
 * resolves. Nothing outside dist/ needs to travel with it.
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = resolve(ROOT, 'tokens/tokens.json');
const OUT = resolve(ROOT, 'tokens/dist');
const PKG = JSON.parse(readFileSync(resolve(ROOT, 'package.json'), 'utf8'));

const T = JSON.parse(readFileSync(SRC, 'utf8'));
const VERSION = T.$meta.version;

/* ---------- helpers ---------------------------------------------------- */

const at = (path) => path.split('.').reduce((o, k) => (o ?? {})[k], T);

/** Resolve {a.b.c} references to their literal $value, recursively. */
function deref(value, seen = 0) {
  if (typeof value !== 'string' || seen > 10) return value;
  const m = value.match(/^\{([^}]+)\}$/);
  if (!m) return value;
  const node = at(m[1]);
  if (node == null) throw new Error(`Unresolved token reference: ${value}`);
  return deref(typeof node === 'object' ? node.$value ?? node.light : node, seen + 1);
}

const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
const camel = (s) => s.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
const CONST = (s) => kebab(s).replace(/-/g, '_').toUpperCase();

/** [ [cssVarName, lightValue, darkValue|null], ... ] in emit order. */
function flatten() {
  const rows = [];
  const push = (name, light, dark = null) => rows.push([name, light, dark]);

  for (const [family, shades] of Object.entries(T.color)) {
    if (family.startsWith('$')) continue;
    for (const [shade, tok] of Object.entries(shades)) {
      if (shade.startsWith('$')) continue;
      push(`color-${kebab(family)}-${shade}`, deref(tok.$value));
    }
  }
  for (const [name, tok] of Object.entries(T.semantic)) {
    if (name.startsWith('$')) continue;
    push(kebab(name), deref(tok.light), deref(tok.dark));
  }
  for (const [k, tok] of Object.entries(T.space)) {
    if (k.startsWith('$')) continue;
    push(`space-${k}`, tok.$value);
  }
  for (const [k, tok] of Object.entries(T.size)) {
    if (k.startsWith('$')) continue;
    push(kebab(k), tok.$value);
  }
  push('font-sans', T.type.family.sans.$value);
  push('font-mono', T.type.family.mono.$value);
  for (const [k, v] of Object.entries(T.type.scale)) {
    if (k.startsWith('$')) continue;
    push(`text-${k}`, v.size);
    push(`leading-${k}`, v.leading);
    push(`tracking-${k}`, v.tracking);
  }
  for (const [k, tok] of Object.entries(T.type.weight)) {
    if (k.startsWith('$')) continue;
    push(`weight-${kebab(k)}`, tok.$value);
  }
  for (const [k, tok] of Object.entries(T.motion.duration)) {
    if (k.startsWith('$')) continue;
    push(`duration-${k}`, tok.$value);
  }
  for (const [k, tok] of Object.entries(T.motion.ease)) {
    if (k.startsWith('$')) continue;
    push(`ease-${k}`, tok.$value);
  }
  for (const [k, tok] of Object.entries(T.elevation)) {
    if (k.startsWith('$')) continue;
    // Elevation references a themed color; keep it as a live var in CSS and
    // bake the light value everywhere else.
    push(`elevation-${k}`, tok.$value.replace(/\{semantic\.(\w+)\}/g, (_, n) => `var(--snm-${kebab(n)})`),
                           tok.$value.replace(/\{semantic\.(\w+)\}/g, (_, n) => `var(--snm-${kebab(n)})`));
  }
  return rows;
}

const ROWS = flatten();
const lightOnly = ROWS.filter(([, , d]) => d === null);
const themed = ROWS.filter(([, , d]) => d !== null);
const bakedLight = (v) => v.replace(/var\(--snm-([a-z0-9-]+)\)/g, (_, n) => {
  const row = ROWS.find(([name]) => name === n);
  return row ? row[1] : 'transparent';
});

const banner = (c1, c2 = '') =>
  `${c1} Swiss Neo-Monolith design tokens v${VERSION}\n${c1} GENERATED by scripts/build-tokens.mjs — do not edit.\n${c1} Source of truth: tokens/tokens.json${c2 ? '\n' + c2 : ''}\n`;

/* ---------- CSS -------------------------------------------------------- */

const cssVars = (rows, idx, ind = '  ') =>
  rows.map(([n, l, d]) => `${ind}--snm-${n}: ${idx === 2 && d !== null ? d : l};`).join('\n');

const css = `/*\n${banner(' *')} */

:root {
  color-scheme: light;
${cssVars(lightOnly, 1)}

${cssVars(themed, 1)}
}

/* Dark theme. The explicit [data-theme] attribute always wins over the
   OS preference, in both directions. */
@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
    color-scheme: dark;
${cssVars(themed, 2, '    ')}
  }
}

:root[data-theme='dark'] {
  color-scheme: dark;
${cssVars(themed, 2)}
}

:root[data-theme='light'] {
  color-scheme: light;
${cssVars(themed, 1)}
}

/* SNM-CANON-01 — zero radius is structural, not decorative. */
@layer base {
  *, *::before, *::after { border-radius: 0; }
  .snm-pulse { border-radius: 9999px; } /* SNM-ALLOW C01 — the one sanctioned exception */
}

@media (prefers-reduced-motion: reduce) {
  :root {
    --snm-duration-fast: 0ms;
    --snm-duration-base: 0ms;
    --snm-duration-slow: 0ms;
  }
}
`;

/* ---------- SCSS ------------------------------------------------------- */

const scss = `//\n${banner('//')}\n` +
  ROWS.map(([n, l]) => `$snm-${n}: ${bakedLight(l)};`).join('\n') + '\n';

/* ---------- TypeScript ------------------------------------------------- */

const tsEntries = ROWS.map(([n, l, d]) =>
  `  '${camel(n)}': { light: ${JSON.stringify(bakedLight(l))}, dark: ${JSON.stringify(bakedLight(d ?? l))}, cssVar: '--snm-${n}' },`
).join('\n');

const ts = `/*\n${banner(' *')} */

export type Theme = 'light' | 'dark';

export interface Token {
  light: string;
  dark: string;
  cssVar: string;
}

export const snmVersion = '${VERSION}' as const;

export const tokens = {
${tsEntries}
} as const satisfies Record<string, Token>;

export type TokenName = keyof typeof tokens;

/** Literal value for a token in a given theme — for canvas, SVG, email, PDF. */
export const token = (name: TokenName, theme: Theme = 'light'): string =>
  tokens[name][theme];

/** CSS custom-property reference — the preferred form inside stylesheets. */
export const cssVar = (name: TokenName): string => \`var(\${tokens[name].cssVar})\`;
`;

/* ---------- Tailwind preset ------------------------------------------- */

const v = (n) => `var(--snm-${n})`;
const map = (rows, strip) => Object.fromEntries(
  rows.filter(([n]) => n.startsWith(strip))
      .map(([n]) => [n.slice(strip.length), v(n)])
);

const tw = `/*\n${banner(' *')} */

/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    // Deliberately replacing (not extending) the defaults: an off-palette
    // colour or an off-scale space value should fail to compile.
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
${['bg','bg-raised','bg-sunken','bg-inverse','text','text-muted','text-inverse','text-accent',
   'accent','accent-press','border','border-strong','focus','overlay','danger','warn','info']
   .map(n => `      '${n}': ${JSON.stringify(v(n))},`).join('\n')}
${Object.entries(T.color).filter(([f]) => !f.startsWith('$')).flatMap(([f, shades]) =>
   Object.keys(shades).filter(s => !s.startsWith('$'))
     .map(s => `      '${kebab(f)}-${s}': ${JSON.stringify(v(`color-${kebab(f)}-${s}`))},`)).join('\n')}
    },
    spacing: {
${Object.keys(T.space).filter(k => !k.startsWith('$')).map(k => `      '${k}': ${JSON.stringify(v(`space-${k}`))},`).join('\n')}
      px: '1px',
      full: '100%',
    },
    borderRadius: { none: '0px', full: '9999px' }, // SNM-ALLOW C01 — 'full' exists for the pulse dot alone
    borderWidth: { 0: '0', DEFAULT: '1px', 2: '2px', 3: '3px' },
    fontFamily: {
      sans: [${JSON.stringify(T.type.family.sans.$value)}],
      mono: [${JSON.stringify(T.type.family.mono.$value)}],
    },
    fontSize: {
${Object.entries(T.type.scale).filter(([k]) => !k.startsWith('$')).map(([k, s]) =>
  `      '${k}': [${JSON.stringify(v(`text-${k}`))}, { lineHeight: ${JSON.stringify(v(`leading-${k}`))}, letterSpacing: ${JSON.stringify(v(`tracking-${k}`))} }],`).join('\n')}
    },
    fontWeight: {
${Object.keys(T.type.weight).filter(k => !k.startsWith('$')).map(k => `      ${kebab(k)}: ${JSON.stringify(v(`weight-${kebab(k)}`))},`).join('\n')}
    },
    boxShadow: {
      none: 'none',
${Object.keys(T.elevation).filter(k => !k.startsWith('$') && k !== '0').map(k => `      '${k}': ${JSON.stringify(v(`elevation-${k}`))},`).join('\n')}
    },
    transitionDuration: {
${Object.keys(T.motion.duration).filter(k => !k.startsWith('$')).map(k => `      ${k}: ${JSON.stringify(v(`duration-${k}`))},`).join('\n')}
      DEFAULT: ${JSON.stringify(v('duration-base'))},
    },
    transitionTimingFunction: {
${Object.keys(T.motion.ease).filter(k => !k.startsWith('$')).map(k => `      ${k}: ${JSON.stringify(v(`ease-${k}`))},`).join('\n')}
      DEFAULT: ${JSON.stringify(v('ease-mech'))},
    },
    extend: {
      maxWidth: { content: ${JSON.stringify(v('content-max'))}, prose: ${JSON.stringify(v('prose-max'))} },
      height:   { header: ${JSON.stringify(v('header-h'))}, 'header-lg': ${JSON.stringify(v('header-h-lg'))} },
      minHeight: {
        // SNM-LAY-02: dvh, never vh.
        stage: 'calc(100dvh - var(--snm-header-h))',
        'stage-lg': 'calc(100dvh - var(--snm-header-h-lg))',
      },
    },
  },
  plugins: [],
};
`;

/* ---------- Python (ReportLab / WeasyPrint / matplotlib) --------------- */

const py = `"""\n${banner('#').split('\n').map(l => l.replace(/^# ?/, '')).join('\n')}"""

VERSION = "${VERSION}"

LIGHT = {
${ROWS.map(([n, l]) => `    ${JSON.stringify(camel(n))}: ${JSON.stringify(bakedLight(l))},`).join('\n')}
}

DARK = {
${ROWS.map(([n, l, d]) => `    ${JSON.stringify(camel(n))}: ${JSON.stringify(bakedLight(d ?? l))},`).join('\n')}
}


def token(name: str, theme: str = "light") -> str:
    """Literal token value. Raises on an unknown name rather than silently
    falling back — an off-palette colour should break the build."""
    table = DARK if theme == "dark" else LIGHT
    return table[name]


def rgb(name: str, theme: str = "light"):
    """Token as a 0..1 RGB tuple, for ReportLab / matplotlib."""
    h = token(name, theme).lstrip("#")
    if len(h) != 6:
        raise ValueError(f"{name} is not a plain hex colour: {h!r}")
    return tuple(int(h[i:i + 2], 16) / 255 for i in (0, 2, 4))
`;

/* ---------- Dart (Flutter) -------------------------------------------- */

const dartColor = ([n, l], theme) => {
  const val = bakedLight(theme === 'dark' ? (ROWS.find(r => r[0] === n)[2] ?? l) : l);
  const m = val.match(/^#([0-9a-f]{6})$/i);
  return m ? `  static const Color ${camel(n)} = Color(0xFF${m[1].toUpperCase()});` : null;
};

const dart = `//\n${banner('//')}
import 'package:flutter/material.dart';

class SnmLight {
${ROWS.map(r => dartColor(r, 'light')).filter(Boolean).join('\n')}
}

class SnmDark {
${ROWS.map(r => dartColor(r, 'dark')).filter(Boolean).join('\n')}
}

class SnmSpace {
${Object.entries(T.space).filter(([k]) => !k.startsWith('$'))
  .map(([k, t]) => `  static const double s${k} = ${parseFloat(t.$value)};`).join('\n')}
}

class SnmType {
  static const String sans = 'Inter';
  static const String mono = 'JetBrainsMono';
${Object.entries(T.type.scale).filter(([k]) => !k.startsWith('$'))
  .map(([k, s]) => `  static const double ${camel('size-' + k)} = ${parseFloat(s.size)};`).join('\n')}
}

/// SNM-CANON-01 — zero radius everywhere.
const BorderRadius snmRadius = BorderRadius.zero;
`;

/* ---------- package manifest ------------------------------------------- */

/* Makes the vendored directory a real package: `npm i file:./vendor/snm`
 * resolves every specifier documented in references/10-web.md. The version is
 * taken from tokens.json so the manifest can never disagree with the tokens it
 * ships — scripts/check-canon.mjs asserts the two against package.json. */
const pkg = {
  name: '@snm/tokens',
  version: VERSION,
  description: 'Swiss Neo-Monolith design tokens — generated bindings. Source: tokens/tokens.json.',
  license: PKG.license,
  author: PKG.author,
  type: 'module',
  sideEffects: ['*.css', '*.scss'],
  exports: {
    '.': { types: './tokens.ts', default: './tokens.ts' },
    './tokens.css': './tokens.css',
    './tokens.scss': './tokens.scss',
    './tokens.ts': './tokens.ts',
    './tokens.py': './tokens.py',
    './tokens.dart': './tokens.dart',
    './tokens.resolved.json': './tokens.resolved.json',
    './tailwind.preset.cjs': './tailwind.preset.cjs',
    './eslint-snm.cjs': './eslint-snm.cjs',
    './package.json': './package.json',
  },
};

/* ---------- lint config (copied in, so the package is self-contained) --- */

const lintSrc = readFileSync(resolve(ROOT, 'assets/web/eslint-snm.cjs'), 'utf8');
const lint = `/*\n${banner(' *', ' * Copied from assets/web/eslint-snm.cjs — edit that file, then rebuild.')} */\n\n` +
  lintSrc.replace(/^\/\*\*[\s\S]*?\*\/\n\n/, '');

/* ---------- resolved JSON --------------------------------------------- */

const resolved = {
  $meta: { ...T.$meta, generated: true },
  tokens: Object.fromEntries(ROWS.map(([n, l, d]) => [n, { light: bakedLight(l), dark: bakedLight(d ?? l) }])),
  print: T.print,
};

/* ---------- write ------------------------------------------------------ */

mkdirSync(OUT, { recursive: true });
const files = {
  'tokens.css': css,
  'tokens.scss': scss,
  'tokens.ts': ts,
  'tailwind.preset.cjs': tw,
  'tokens.py': py,
  'tokens.dart': dart,
  'tokens.resolved.json': JSON.stringify(resolved, null, 2) + '\n',
  'eslint-snm.cjs': lint,
  'package.json': JSON.stringify(pkg, null, 2) + '\n',
};

for (const [name, body] of Object.entries(files)) {
  writeFileSync(resolve(OUT, name), body, 'utf8');
  console.log(`  wrote tokens/dist/${name}  (${body.length.toLocaleString()} B)`);
}
console.log(`\nSwiss Neo-Monolith v${VERSION} — ${ROWS.length} tokens compiled.`);
